[package]
name = "qml_plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
cxx = "1.0.198"
cxx-qt = "0.9.1"
cxx-qt-lib = "0.9.1"
duckduckgo = "0.3.3"
kalk = "3.2.3"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
smart-calculator = "1.0.3"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
unwrap-print = "0.1.1"
unwrap-retry = "0.5.0"

[build-dependencies]
cxx-qt-build = "0.9.1"

[package.metadata.cargo-machete]
ignored = ["cxx"]
