[package]
name = "qml_plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
cxx = "1.0.198"
cxx-qt = "0.9.1"
cxx-qt-lib = "0.9.1"
smart-calculator = "1.0.3"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
cxx-qt-build = "0.9.1"
